CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    user_id INT NOT NULL REFERENCES users (id),
    name VARCHAR(32) NOT NULL,
    description VARCHAR(200) NOT NULL
)