CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users (id),
    name VARCHAR(32) NOT NULL,
    description VARCHAR(200) NOT NULL
)